apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: demo
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: db-connect
      mountPath: /opt
  volumes:
  - name: db-connect
    configMap:
      name: db-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: demo
data:
  db-port: "3306"
  db-pass: "password" 

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-replicaset
  labels:
    app: httpd_app
    type: front-end
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd_app
      type: front-end
  template:
    metadata:
      labels:
        app: httpd_app
        type: front-end
    spec:
      containers:
      - name: httpd-container
        image: httpd:latest